### ISSUE TITLE
Firefox; extensions won't install

### ISSUE THREAD

**Issue by jim-collier** [ethanhs/WSL-Programs#115]
When adding extensions, they will download fine, but get "stuck" at "Installing". Even downloading the extensions directly to a folder, then dragging 'n dropping to the "Extensions" page, has the same result.

Firefox v 57.0.1 (64-bit)
Extensions: Tested on numerous random top-suggested. (Including after WSL subsystem restarts and Windows reboots.)

Windows 10 Pro build 16299.rs3_release.170928-1534
Windows-native X server: VcXsrvv 1.19.3.4 (64-bit)
Ubuntu 16.04.3 LTS (latest App Store WSL version as of 2017-12-01; minimal configuration/customization)
XFCE4: 4.12.0
Xserver (Ubuntu): 1.18.4
Bash: 4.3.48(1)

**Comment by emmatyping** [comment]
Please feel free to file a PR with the status.
