### ISSUE TITLE
Please update list of supported apps

### ISSUE THREAD

**Issue by WSLUser** [ethanhs/WSL-Programs#120]
I've notice many things are listed with an older build and some such as Electron could use additional testing. Electron specifically should be working within Insider builds (along with anything depending on it such as Atom if I recall correctly). Also notice Pulse Audio isn't there. There's a custom PPA  (see https://launchpad.net/%7Etherealkenc/+archive/ubuntu/wsl-pulseaudio) that allows it to work.

**Comment by Biswa96** [comment]
Atom text editor also works. I've installed xfce4 in Ubuntu Bionic WSL. Then download `atom-amd64.deb` file from https://github.com/atom/atom/releases and install it with `sudo dpkg -i atom-amd64.deb`. If it shows any packages are missing then run `sudo apt-get install -f` and try the previous `dpkg -i` command again. 

![Atom_in_xfce4_in_Ubuntu](https://user-images.githubusercontent.com/31443074/36967096-ce62bbf2-2084-11e8-9e00-805c3defaa64.PNG)

**Comment by emmatyping** [comment]
Hi, this is a community powered list, which means that PRs are welcome, but I don't really work on it myself. Feel free to submit PRs!

**Comment by yecril71pl** [comment]
The request queue shows that you do not care about PRs either :-(

**Comment by emmatyping** [comment]
Hello @yecril71pl. I do care, I've just been very busy with other things that are higher priority to me. I'll try to merge open PRs later this week.

**Comment by emmatyping** [comment]
I just merged a bunch of PRs. I will try to be more timely in doing so in future.
