### ISSUE TITLE
GIMP not working with WSL2 via GWSL?

### ISSUE THREAD

**Issue by Andrew-J-Larson** [ethanhs/WSL-Programs#137]
Using the Windows Store app located at https://www.microsoft.com/en-us/p/gwsl/9nl6kd1h33v3?activetab=pivot:overviewtab

**Comment by Andrew-J-Larson** [comment]
A few more details I forgot to mention. I had to setup an auto start for dbus manually, but I don't believe that is the problem.

What happens though is when I start GIMP, it'll load, but once it gets to the default GUI window, it's pretty empty and then seconds later crashes with (x-server is on multi-window mode, otherwise, GIMP will work when on single/fullscreen mode):

```bash
gimp: Fatal IO error 0 (Success) on X server [ip-address]:0.0.

(script-fu:10166): LibGimpBase-WARNING **: 15:13:20.998: script-fu: gimp_wire_read(): error
```

**Comment by davidcostanzo** [comment]
I have the same experience.  I have two bits of information to add:
1) The X Server crashes, which I expect is why Gimp has the read error and exits.
2) Both GWSL and VcXsrv Windows X Server crash (in multi-window mode as TheAlienDrew mentioned).

**Comment by starXultra** [comment]
Same problem pls fix. This is one of the apps i really want to use

**Comment by Andrew-J-Larson** [comment]
> Same problem pls fix. This is one of the apps i really want to use
> 

Try using WSLg instead, now that Microsoft has its own graphical system implementation.

**Comment by davidcostanzo** [comment]
> > Same problem pls fix. This is one of the apps i really want to use
> 
> Try using WSLg instead, now that Microsoft has it's own graphical system implementation.

Good thinking.  I installed "Windows Subsystem for Linux Preview" and was able to start Gimp from Ubuntu on Windows 11 v10.0.22000.

**Comment by Andrew-J-Larson** [comment]
Closing this, too out of date.
