### ISSUE TITLE
Add grep to the table

### ISSUE THREAD

**Issue by trevren11** [ethanhs/WSL-Programs#16]
I am not sure if this would be worth adding to the list, but grep mostly works with some shortcomings such as [this](https://github.com/Microsoft/BashOnWindows/issues/450) issue with passwords being printed to the console.

**Comment by emmatyping** [comment]
Perhaps with a warning about the password in the note. I would give it a lower rating due to the seriousness of the bug. Interested to hear other opinions however.

**Comment by emmatyping** [comment]
Alright, I will probably add something about grep in the coming days if no one else has opinions. 

pinging @all to see what people think.
