### ISSUE TITLE
zsh install and it can run oh-my-zsh

### ISSUE THREAD

**Issue by aliceinwire** [ethanhs/WSL-Programs#19]
zsh install and it can run oh-my-zsh
oh-my-zsh are working as far i can see.
chsh -s $(which zsh) #have almost no effect because anyway you need to start command promt and switch with bash command that will run bash.
i didn't check if there is a way for start directly on zsh.

**Comment by emmatyping** [comment]
Thanks for your investigations, if you would like, you can file a pull request with relevant info.

**Comment by aliceinwire** [comment]
added this to the end of .bashrc
export SHELL=/bin/zsh
[ -z "$ZSH_VERSION" ] && exec /bin/zsh -l

and now is starting zsh when i click bash on windows icon
bit forced but is working well

**Comment by Eun** [comment]
I got a similar approach: 
https://blog.salzmann.to/windows10/linux/2016/08/03/changing-the-shell-windows-subsystem-for-linux.html
