### ISSUE TITLE
Mono Issues

### ISSUE THREAD

**Issue by turbo** [ethanhs/WSL-Programs#21]
Mono 4.4 breaks some mkbundle functionality. Stick with 4.2 for now. Info [here](https://github.com/mono/website/issues/199#issuecomment-230333018).

Please close this issue only when the above bug is resolved. Or, if you desire, add a warning to the Mono entry for the time being.

**Comment by turbo** [comment]
> Downgrading mono etc. to do local builds work is Ok for now.

Update: It should be safe to use Mono embedding again when 4.6.0 is released (or build from git if the tag updates at [mono/mono](http://github.com/mono/mono)).

**Comment by emmatyping** [comment]
I think I will add something to mono saying use 4.2 for now or 4.6 when it is released. Thanks for the updates!
