### ISSUE TITLE
Add gradle and java versions

### ISSUE THREAD

**Issue by khessels** [ethanhs/WSL-Programs#27]
Add gradle ( and gradlew)
And the different java versions (or the versions you are concentrating on)
What java do you mean (oracle, openjdk , ...) what version 7, 8 , ...

**Comment by ThaJay** [comment]
just try and run it, a lot of things work now.
```bash
PS E:\dev> bash
/mnt/e/dev $ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
