### ISSUE TITLE
ADB functionality. 

### ISSUE THREAD

**Issue by ReVanTis** [ethanhs/WSL-Programs#29]
You can actually operate adb on WSL. 
Well, on some level. 

By default, WSL will install adb of version 1.10.31. 
If you pick the very same version on Windows and start adb server (adb start-server) on Windows, you can actually see and access android devices on WSL. 

I assume adb server's inter-process communication is based on network model (on port 5037 as you often see). 
So even the server is running on windows, it does not break the client running on WSL as long as they recognize each other with same version number. 

Have fun hacking WSL :D

**Comment by emmatyping** [comment]
So for example, if you `adb devices` it lists connected devices from bash? I would be very surprised if this is the case.

**Comment by ReVanTis** [comment]
![adb on bash](https://cloud.githubusercontent.com/assets/7135398/17540401/6b94e568-5ee8-11e6-8523-b3efa1e4edd8.png)

Hi @ethanhs,
Please kindly have a look :)

**Comment by emmatyping** [comment]
Wow, great! I am glad you found this. :) I will add this to the list and add something in the notes. Thank you!

**Comment by emmatyping** [comment]
Fixed in https://github.com/ethanhs/WSL-Programs/commit/810914cb9f232b0aedd4766fc388aae7477b8013

**Comment by ThaJay** [comment]
Awesome, this would enable me to develop React-Native on device. Will check it out

**Comment by IPWright83** [comment]
I don't believe this works on WSL2? I've got the same ADB version running on both windows and Ubuntu, ensuring I start the windows adb server first (via CMD) and the device list is always empty in the WSL.

**Comment by ThaJay** [comment]
For me it's very simple: Run the production build via WSL and use ADB through Git Bash on CMD (and everything else works there as well).

I only have to remove the build folder and switch my `./android/local.properties` to use the other location for the Android sdk.
```
# Windows (for running the dev server etc.)
# sdk.dir=/C\:\\Users\\name\\AppData\\Local\\Android\\Sdk
# WSL (for making production builds)
sdk.dir=/usr/lib/android-sdk/
```
