### ISSUE TITLE
vim+

### ISSUE THREAD

**Issue by sixhobbits** [ethanhs/WSL-Programs#47]
It is claimed that vim can create new Linux files but not new Windows files. What exactly is meant by this? I have no issues creating files using vim.

Also on the main page it says "Plugins don't work", but under the detailed list it says that they do. Haven't tested extensively, but only one can be right.

**Comment by Krutonium** [comment]
Honestly no idea, there isn't anything preventing that from working.

I suspect that it may be a case of some, but not all, plugins working. Regardless, this question is quite old now. @ethanhs Perhaps we should close this?

**Comment by emmatyping** [comment]
Agreed. Feel free to submit a PR if there are new developments.
