### ISSUE TITLE
Firefox works

### ISSUE THREAD

**Issue by rmcolbert** [ethanhs/WSL-Programs#51]
Firefox 49.0 appears to work though it complains about multithreading breaking the sandbox.  Have not tested media playback but based on other comments, I expect audio to fail.

To run, download & install an X11 server like VcXsrv or XMing.
Install Firefox w/ apt-get install firefox -y

**Comment by emmatyping** [comment]
Wow! That is amazing! If you'd like, you can submit a PR and include your findings.

**Comment by Krutonium** [comment]
Firefox now listed as working
