### ISSUE TITLE
Java works

### ISSUE THREAD

**Issue by ThaJay** [ethanhs/WSL-Programs#58]
```bash
PS E:\dev> bash
/mnt/e/dev $ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
haven't been able to use it much because I did not get adb to work yet.
Will look into the corresponding issue on this repo.

**Comment by emmatyping** [comment]
ADB probably doesn't work because WSL doesn't have access to devices over USB. IIRC, you can set up a localhost network, pipe it through windows and then use the ADB ip server. Not the cleanest solution, but I've heard it work for some people.

**Comment by ThaJay** [comment]
ADB actually works out of the box just like documented here. Start the server on Windows (for example just type `adb devices` in powershell) Then check `adb devices` on bash and it works.

Java also seems to work fine thus far. It's mostly the lack of kvm that's holding me back at the moment.

**Comment by emmatyping** [comment]
I added a note about java 1.8
