### ISSUE TITLE
Thunar works

### ISSUE THREAD

**Issue by JLIT0** [ethanhs/WSL-Programs#59]
Thunar file manager using Xming works to access files, although icon thumbnails are not shown.

It can associate and open file extensions with installed Linux applications, but not Windows ones.

**Comment by emmatyping** [comment]
Please file a PR and add to the chart, thanks!

**Comment by Krutonium** [comment]
Thunar is used under XFCE4, which is part of the XFCE4 Desktop, which is listed as working
