### ISSUE TITLE
WINE doesn't work

### ISSUE THREAD

**Issue by JLIT0** [ethanhs/WSL-Programs#60]
Funnily enough, WINE doesn't work on WSL.  The only barrier to this however seems to be the inability to execute i386 libraries on WSL.

_WINE working on WSL may not however be a crazy idea.  It has increased backward compatibility with older software, especially 16-bit applications which cannot run on 64 bit Windows due to the lack of NTDVM._

**Comment by emmatyping** [comment]
Actually, I have seen some people getting it to work. I haven't seen any documented method to get it to work, but its possible.

**Comment by WSLUser** [comment]
Love to see this documentation if it can work. Even the latest WINE beta doesn't work out of box

**Comment by emmatyping** [comment]
Hi, this is a community run list, if you'd like to contribute, feel free!
