### ISSUE TITLE
ifconfig now works on WSL

### ISSUE THREAD

**Issue by ShadowEO** [ethanhs/WSL-Programs#61]
Not entirely sure which version brought the fix for this, but running 14986, I can run ifconfig and ip and get network information from all available interfaces. I haven't tested any of the commands to set network configuration.

**Comment by emmatyping** [comment]
That is great! Could you make a PR to add it to the list?

**Comment by Krutonium** [comment]
This is in the List as of now, can be closed.

**Comment by emmatyping** [comment]
Good catch.
