### ISSUE TITLE
Section for interesting parts/in depth documentation

### ISSUE THREAD

**Issue by stevenwalton** [ethanhs/WSL-Programs#8]
So we have a section for functionality of specific programs but it would also be nice to have a section for interesting quirks about the system that we find. 
For example:
`uname -v` gives returns `#1 PREEMPT Thu Aug 1 17:06:05 CST`
Or that keyboard shortcuts do not work. 

So I have a few ideas how this could work. 
1) Have a different section in the README for quirks 
2) Have a separate file
3) Start a wiki where we can also put more documentation about programs and we can organize them better. 

I have some updates to the README that I will be pushing soon but I'll wait till I get an answer to this. 

On a side note, has anyone told Microsoft about this repo?

**Comment by emmatyping** [comment]
I'll start with the last question, the answer, I'm not sure.

 As to observations, maybe a different file would be the best. I like the idea. Perhaps name it OBSERVATIONS.md or something like that.

**Comment by stevenwalton** [comment]
Then you mind if I create two files? One called `Observations.md` and another called `Program_Details.md`
For example when I was installing `pip` I broke `apt`. Don't want people to run into that issue. 

I'll make a pull request with that.

**Comment by emmatyping** [comment]
Sounds good! :+1:
